### ISSUE TITLE
Script to run drop_entire_block using llama-3.1-8b

### ISSUE THREAD

**Issue by chijames** [IST-DASLab/EvoPress#2]
Hi,

There are many arguments required by the file evo_drop_search.py. Could you share a bash script that sets the parameters you used in the paper for dropping entire blocks (Table 9 in Appendix D), please?

Thanks.

**Comment by OliverSieberling** [comment]
Hello,

Thanks for your interest!

I have added the script we used to run evo_drop_search.py and some other scripts into the example_script folder. You might want to reduce the number of evaluation datasets - we tracked all of them for the paper, but it's not necessary for observing convergence. You might not even need hold out data at all, we never observed overfitting to calibration data.
