### ISSUE TITLE
Scrong method settings

### ISSUE THREAD

**Issue by rG223** [IST-DASLab/EvoPress#4]
I not sure the setting of scrong methods for deep pruning. I try to use following settings.
```python
MODEL="mistralai/Mistral-7B-v0.3"
CALIB_DATA="fineweb_edu"

SEQUENCE_LENGTH=8192
CALIB_TOKENS=131072


CONFIG_PATH="/home/yerg/EvoPress/log"  # Modify this path to point to your local folder

echo "Running with SPARSITY=$SPARSITY"

python drop_scoring.py  \
    --model_name_or_path $MODEL \
    --calibration_data $CALIB_DATA \
    --calibration_tokens $CALIB_TOKENS \
    --calibration_sequence_length $SEQUENCE_LENGTH \
    --eval_sequence_length $SEQUENCE_LENGTH \
    --sparsities 0.125 0.25 0.375 0.5 0.625 0.75 \
    --dtype float16 \
    --attn_implementation flash_attention_2 \
    --use_fast_tokenizer \
    --eval_every 5 \
    --scoring_method 'cosine_similarity' \
    --eval_datasets "fineweb_edu" "wikitext2" "c4" \
    --log_wandb \
```
For sparsity=0.125, the result is fineweb_edu: 8.39, wikitext2: 7.19, and c4: 10.18.
This experiment looks great, can you share your settings for scoring methods?

**Comment by OliverSieberling** [comment]
Hello,

the methods compared against in the paper can be reproduced by setting scoring_method to 
- "cosine_similarity" (for ShortGPT)
-  "perplexity" (for Shortened Llama)
-  "window_cosine_similarity" (for Gromov et al.)
- "norm_ratio" (for Weight Subcloning)

We also implemented "kl_div", "l2", "l2_normalized" for another experiment (see Appendix: Correlation of Scores with Perplexity). The results you get seem correct and are more or less the same as the ones we report in Table 9 (Depth pruning of Mistral-7B-v0.3).

**Comment by rG223** [comment]
I see. Thank you for your explanation.
