### ISSUE TITLE
Unstructured Sparse Pruning

### ISSUE THREAD

**Issue by rG223** [IST-DASLab/EvoPress#5]
Hello,

I have several questions. Thank you in advance for your help!

(1) I was wondering if you could kindly provide example commands for running prune.py, owl_prune.py, and evo_prune_search.py. Some required parameters appear to lack default values, and I’m uncertain about the correct inputs to use.

(2) How do I set some parameters in lmeval.py? I run the following script:：
```python
python lmeval.py  \
    --model_args "pretrained=mistralai/Mistral-7B-v0.3" \
    --tasks "arc_easy,arc_challenge,piqa,winogrande,hellaswag" \
    --drop_layer_config "/home/yerg/EvoPress/log/layer_drop_config.txt"
```
I got an error, UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 1: invalid start byte.
Traceback (most recent call last):
 File "/mnt/data/home/yerg/EvoPress/lmeval.py", line 413, in <module>
     cli_evaluate()
File "/mnt/data/home/yerg/EvoPress/lmeval.py", line 360, in cli_evaluate
    results = evaluator.simple_evaluate(
File "/home/yerg/anaconda3/envs/llm/lib/python3.10/site-packages/lm_eval/evaluator.py", line 124, in simple_evaluate
    task_dict = lm_eval.tasks.get_task_dict(tasks)
File "/home/yerg/anaconda3/envs/llm/lib/python3.10/site-packages/lm_eval/tasks/__init__.py", line 250, in get_task_dict
    task_name: get_task(task_name=task_element, config=config),
File "/home/yerg/anaconda3/envs/llm/lib/python3.10/site-packages/lm_eval/tasks/__init__.py", line 192, in get_task
     return TASK_REGISTRY\[task_name\](config=config) 
File "/home/yerg/anaconda3/envs/llm/lib/python3.10/site-packages/lm_eval/api/task.py", line 633, in __init__
    self.download(self.config.dataset_kwargs)
File "/home/yerg/anaconda3/envs/llm/lib/python3.10/site-packages/lm_eval/api/task.py", line 730, in download
    self.dataset = datasets.load_dataset( 
File "/home/yerg/anaconda3/envs/llm/lib/python3.10/site-packages/datasets/load.py", line 2606, in load_dataset
     builder_instance = load_dataset_builder(
File "/home/yerg/anaconda3/envs/llm/lib/python3.10/site-packages/datasets/load.py", line 2277, in load_dataset_builder
     dataset_module = dataset_module_factory(
File "/home/yerg/anaconda3/envs/llm/lib/python3.10/site-packages/datasets/load.py", line 1923, in dataset_module_factory
    raise e1 from None
File "/home/yerg/anaconda3/envs/llm/lib/python3.10/site-packages/datasets/load.py", line 1875, in dataset_module_factory
    can_load_config_from_parquet_export = "DEFAULT_CONFIG_NAME" not in f.read()
File "/home/yerg/anaconda3/envs/llm/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)

**Comment by rG223** [comment]
The second problem can be solved by https://github.com/huggingface/datasets/issues/6760.
`Datasets` package is needed to downgrade to 2.14.6 version for runing lmeval.py script.

**Comment by rG223** [comment]
Hello, could you give me some example scripts for prune.py, owl_prune.py, and evo_prune_search.py? 
I run a following script:
```python
MODEL="mistralai/Mistral-7B-v0.3"
CALIB_DATA="fineweb_edu"

SEQUENCE_LENGTH=8192
CALIB_TOKENS=131072

SPARSITY=0.375 # 12 removed blocks for Mistral-7B-v0.3 (32 blocks in total)

torchrun --nnodes=1 --nproc-per-node=2 \
    prune.py \
    --model_name_or_path $MODEL \
    --block_modules "model.layers" \
    --pre_block_modules "model.embed_tokens" \
    --calibration_data $CALIB_DATA \
    --low_cpu_mem_usage \
    --cpu_offload_modules \
    --cpu_offload_activations \
    --sparsity $SPARSITY \
    --prunable_modules ".*self_attn.*|.*mlp.*" \
    --calibration_sequence_length $SEQUENCE_LENGTH \
    --dtype float16 \
    --attn_implementation flash_attention_2 \
    --save_dir "/home/yerg/EvoPress/model_path"
```
It raises an error:
 File "/mnt/data/home/yerg/EvoPress/src/fast_obc.py", line 137, in step [rank0]:     thr, _ = torch.kthvalue(scores.view(-1), round(w_blk.numel() * sparsity)) 
 [rank0]: RuntimeError: kthvalue(): selected number k out of range for dimension 0 E1217 08:33:56.074000 139726438053696 

Maybe ``thr, _ = torch.kthvalue(scores.view(-1), round(w_blk.numel() * sparsity))`` should be changed to
``thr, _ = torch.kthvalue(scores.view(-1), max(round(w_blk.numel() * sparsity), 1))`` ?

By the way, ``thr, _ = torch.kthvalue(scores.view(-1), max(round(w_blk.numel() * sparsity), 1))`` appears to fix the bug. However, I am unsure whether the generated weight file (e.g., model.layer.0.mlp.down.proj) is correct.

**Comment by OliverSieberling** [comment]
Hello,

I added the scripts for prune.py, evo_prune_search.py, owl_prune.py and lmeval.py to the scripts folder. I hope this fixes the issues. Please let me know if you still encounter any problems.

**Comment by rG223** [comment]
Thank you very much for providing the script. When I ran prune.py using the following script, it worked fine:
```python
MODEL="mistralai/Mistral-7B-v0.3"
SEQUENCE_LENGTH=8192
SPARSITY=0.5

CALIB_DATA="fineweb_edu"
NUM_TOKENS=8388608 # 1024*8192
#WEIGHTS_DIFF=1000000
NUM_LEVELS=8

SAVE_DIR="/home/yerg/EvoPress/model_path_Meta-Llama-3"  # Modify this path to point to your local folder (will be used by prune_search.sh)

# For Llama models, the pre_block_modules should be "model.embed_tokens model.rotary_emb"
torchrun --nnodes=1 --nproc-per-node=2 prune.py \
    \
    --model_name_or_path $MODEL \
    --prunable_modules '.*layers.*((q|k|v|o|gate|up|down)_proj)$' \
    --pre_block_modules model.embed_tokens \
    --block_modules model.layers \
    \
    --calibration_data $CALIB_DATA \
    --calibration_tokens $NUM_TOKENS \
    --calibration_sequence_length $SEQUENCE_LENGTH \
    \
    --sparsity $SPARSITY \
    --num_levels $NUM_LEVELS \
    \
    --low_cpu_mem_usage \
    --cpu_offload_modules \
    --cpu_offload_activations \
    --verbose \
    \
    --attn_implementation flash_attention_2 \
    --dtype float16 \
    \
    --save_dir $SAVE_DIR
```
However, when I try using ``MODEL="meta-llama/Meta-Llama-3-8B"``, the script doesn't work. Could you help me understand why?

**Comment by OliverSieberling** [comment]
Try adding model.rotary_emb to pre_block_modules, this should help.

**Comment by rG223** [comment]
I'm so sorry, I just noticed that comment. It works now, thanks for your help!

**Comment by rG223** [comment]
> Try adding model.rotary_emb to pre_block_modules, this should help.

Hello, when I run run_owl_prune.sh script, it generates a searching dataset (e.g., the 0.pth in different layers). Then, how to obtain the performance of OWL method on the evaluation datasets? Becuase it has many choices, which one is the model for OWL pruning method?

**Comment by OliverSieberling** [comment]
Hello,

OWL does a hyperparameter sweep, and for each combination of hyperparameters there is a corresponding model. So each of these levels corresponds to one such model (e.g. loading 0.pth for all layers corresponds to one set of hyperparameters). This hyperparameter sweep is not implemented in the OWL codebase. We simply evaluated each of these models and then reported the model with lowest perplexity. You can do this with minimal changes to e.g. evo_prune_search.py by looping over the levels and loading [0, 0, ..., 0], [1, 1, ..., 1], ... as configurations. Since the authors of OWL did not specify how they chose the best model, we simply report the model with lowest perplexity on the eval data directly. While this is in OWL's favor, it shouldn't change much and it's not a competitive method anyway.

**Comment by OliverSieberling** [comment]
Hello @rG223,

OWL includes a hyperparameter sweep, but it's not implemented in their codebase. Since they also didn't specify in the paper how they determine the best model, we decided to simply report the model with lowest eval perplexity. While this may slightly favor OWL, our improvements are so significant that this wasn't a concern. You can evaluate OWL models with minimal changes to e.g. evo_prune_search.py by looping over the levels and loading [0, 0, ..., 0], [1, 1, ..., 1], ... as configurations and then evaluating perplexity (loading e.g. 0.pth for all layers corresponds to the model resulting from one hyperparameter setting).
